dist: trusty
sudo: false
language: node_js
node_js: node

install:
- npm install
- npm install typescript -g
cache:
  directories:
  - $HOME/.npm
script:
- npm run build

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   local-dir: dist
#   on:
#     branch: master

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/